name: release
on:
  push:
    branches: main
env:
  SQLX_OFFLINE: true
jobs:
  build-server:
    name: Build server
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/644969258749/locations/global/workloadIdentityPools/github-action/providers/github-action-provider
          service_account: github-action@dev-smoke-364604.iam.gserviceaccount.com
      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: asia-east1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - id: version
        name: Get version
        run: echo "DOCKER_VERSION=${{ github.sha }}" >> $GITHUB_OUTPUT
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
          tags: asia-east1-docker.pkg.dev/dev-smoke-364604/saka-saka/tcg-scraper:${{ steps.version.outputs.DOCKER_VERSION }}

